# Gradle JVM arguments for optimal React Native compilation
org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.19.10-hotspot
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
hermesEnabled=true
newArchEnabled=false
IS_NEW_ARCHITECTURE_ENABLED=false

